<?php
function rake_distpot( $array = array() )
{
    global $pdo, $tpr, $plyrname;
    $pots     = $array['content'];
    $winners  = $array['winners'];
    $type     = 'Global';
    $tablepot = $tpr['pot'];

    if (count($winners) !== 1)
        return $pots;

    if (!defined('RAKE_TYPE') || !defined('RAKE_COMMISSION_EACHHAND'))
        return $pots;

    if (RAKE_COMMISSION_EACHHAND !== 'yes')
        return $pots;
    
    if (RAKE_TYPE === 'table')
    {
        if (! isset($tpr['rake_comm_pc'], $tpr['rake_comm_cap']))
            return $pots;

        $type    = 'Table';
        $percent = (int) $tpr['rake_comm_pc'];
        $capNum  = (int) $tpr['rake_comm_cap'];
    }
    else
    {
        if (!defined('RAKE_COMMISSION') || !defined('RAKE_COMMISSION_CAP'))
            return $pots;

        $percent = (int) RAKE_COMMISSION;
        $capNum  = (int) RAKE_COMMISSION_CAP;
    }
    
    foreach ($winners as $w => $win)
    {
        $winner     = $w;
        $winnerName = $win['name'];
        $winnerPot  = $win['pot'];
    }

    $percentage = $percent / 100;
    $cap        = $capNum;
    $commission = floor($tablepot * $percentage);
    $comMoney   = round(transfer_from($commission));

    if ($cap > 0 && $comMoney > $cap)
        $commission = transfer_to($cap);

    $pots[$winner] -= $commission;

    $agent           = '';
    $agentCommission = 0;
    $rakeRwdPc       = 0;

    if (\OPSAddon::isActive('agents'))
    {
        $agentS = $pdo->query("SELECT referred_by FROM " . DB_PLAYERS . " WHERE username = '{$winnerName}'");
        $agentF = $agentS->fetch(PDO::FETCH_ASSOC);
        $agent  = $agentF['referred_by'];

        if (! empty($agent))
        {
            $agentS = $pdo->query("SELECT is_agent, rwd_opt_rpc, rake_reward_pc FROM " . DB_PLAYERS . " WHERE username = '{$agent}'");
            $agentF = $agentS->fetch(PDO::FETCH_ASSOC);

            if ($agentF['is_agent'] == 1 && $agentF['rwd_opt_rpc'] == 1)
            {
                $agentPaysys = \OPSAddon::getSetting( 'agents', 'payout_system' );
                $rakeRwdPc   = (int) \OPSAddon::getSetting( 'agents', 'agent_rake_rwd' );
                $potVar      = ($agentPaysys === 'auto') ? 'winpot' : 'refpot';

                if ($agentF['rake_reward_pc'] >= 0)
                    $rakeRwdPc = $agentF['rake_reward_pc'];

                if ($rakeRwdPc > 0)
                    $rakeRwdPc = $rakeRwdPc / 100;

                $agentCommission = $commission * $rakeRwdPc;
                $pdo->query("UPDATE " . DB_STATS . " SET $potVar = $potVar + $agentCommission WHERE player = '{$agent}'");
                $commission = $commission - $agentCommission;

                if ($agentPaysys === 'auto')
                    ag_payout_log($agent, $agentCommission, "Reward " . money_small($agentCommission) . " paid for rake generated by {$winnerName}");
                else
                    ag_payout_log($agent, $agentCommission, "Reward " . money_small($agentCommission) . " pending admin approval for rake generated by {$winnerName}");
            }
        }
    }

    $pdo->query("UPDATE " . DB_STATS . " SET winpot = winpot + $commission WHERE player = '" . RAKE_COMMISSION_USER . "'");
    
    $setting  = "{$type}; {$percent}%;";
    $setting .= ($capNum > 0) ? " \${$capNum} capped;" : ' No cap;';
	$setting .= " Agent " . ($rakeRwdPc * 100) . "%";

    rake_log_insert(array(
        'tableID'          => $tpr['gameID'],
        'historyID'        => 0,
        'player'           => $winnerName,
        'commissioner'     => RAKE_COMMISSION_USER,
        'commission'       => $commission,
        'agent'            => $agent,
        'agent_commission' => $agentCommission,
        'setting'          => $setting
    ));

    return $pots;
}
$addons->add_hook(array(
    'page'     => 'includes/poker_inc.php',
    'location' => 'distpots',
    'function' => 'rake_distpot',
));
