<?php
function rake_winpot( $array = array() )
{
	global $pdo, $tpr, $plyrname;
	$winpot 	= $array['content'];
	$type = 'Global';

	if (!defined('RAKE_TYPE') || !defined('RAKE_COMMISSION_EACHHAND'))
		return $winpot;

	if (RAKE_COMMISSION_EACHHAND === 'yes')
	    return $winpot;

	if (RAKE_TYPE === "table")
	{
		if (! isset($tpr['rake_comm_pc'], $tpr['rake_comm_cap']))
			return $winpot;

		$type    = 'Table';
		$percent = (int) $tpr['rake_comm_pc'];
		$capNum  = (int) $tpr['rake_comm_cap'];
	}
	else
	{
		if (!defined('RAKE_COMMISSION') || !defined('RAKE_COMMISSION_CAP'))
			return $winpot;

		$percent = (int) RAKE_COMMISSION;
		$capNum  = (int) RAKE_COMMISSION_CAP;
	}
	
	$percentage = $percent / 100;
	$cap        = (int) $capNum;
	$commission = floor ($winpot * $percentage);
	$comMoney   = round(transfer_from($commission));

	if ($cap > 0 && $comMoney > $cap)
		$commission = transfer_to($cap);

	$winpot -= $commission;

	$agent           = '';
	$agentCommission = 0;
	$rakeRwdPc       = 0;

	if (\OPSAddon::isActive('agents'))
	{
		$agentS = $pdo->query("SELECT referred_by FROM " . DB_PLAYERS . " WHERE username = '$plyrname'");
		$agentF = $agentS->fetch(PDO::FETCH_ASSOC);
		$agent  = $agentF['referred_by'];

		if (! empty($agent))
		{
			$agentS = $pdo->query("SELECT is_agent, rwd_opt_rpc, rake_reward_pc FROM " . DB_PLAYERS . " WHERE username = '$agent'");
			$agentF = $agentS->fetch(PDO::FETCH_ASSOC);

			if ($agentF['is_agent'] == 1 && $agentF['rwd_opt_rpc'] == 1)
			{
				$agentPaysys = \OPSAddon::getSetting( 'agents', 'payout_system' );
				$rakeRwdPc   = (int) \OPSAddon::getSetting( 'agents', 'agent_rake_rwd' );
				$potVar      = ($agentPaysys === 'auto') ? 'winpot' : 'refpot';

				if ($agentF['rake_reward_pc'] >= 0)
					$rakeRwdPc = $agentF['rake_reward_pc'];

				if ($rakeRwdPc > 0)
					$rakeRwdPc = $rakeRwdPc / 100;

				$agentCommission = $commission * $rakeRwdPc;
				$pdo->query("UPDATE " . DB_STATS . " SET $potVar = $potVar + $agentCommission WHERE player = '{$agent}'");
				$commission = $commission - $agentCommission;

				if ($agentPaysys === 'auto')
					ag_payout_log($agent, $agentCommission, "Reward " . money_small($agentCommission) . " paid for rake generated by {$plyrname}");
				else
					ag_payout_log($agent, $agentCommission, "Reward " . money_small($agentCommission) . " pending admin approval for rake generated by {$plyrname}");
			}
		}
	}

	$setting  = "{$type}; {$percent}%;";
	$setting .= ($capNum > 0) ? " \${$capNum} capped;" : " No cap;";
	$setting .= " Agent " . ($rakeRwdPc * 100) . "%";

	rake_log_insert(array(
    	'tableID'          => $tpr['gameID'],
    	'historyID'        => 0,
    	'player'           => $plyrname,
    	'commissioner'     => RAKE_COMMISSION_USER,
    	'commission'       => $commission,
    	'agent'            => $agent,
    	'agent_commission' => $agentCommission,
    	'setting'          => $setting
    ));

    $pdo->query("UPDATE " . DB_STATS . " SET winpot = winpot + $commission WHERE player = '" . RAKE_COMMISSION_USER . "'");
    return $winpot;
}
$addons->add_hook(array(
	'page'     => 'includes/inc_poker.php',
	'location' => 'winpot_var',
	'function' => 'rake_winpot',
));
